export const ARCANA_COLORS: Record<string, string> = {
  Fool:        'bg-slate-500 text-white',
  Magician:    'bg-red-700 text-white',
  Priestess:   'bg-blue-700 text-white',
  Empress:     'bg-green-700 text-white',
  Emperor:     'bg-yellow-700 text-white',
  Hierophant:  'bg-orange-700 text-white',
  Lovers:      'bg-pink-600 text-white',
  Chariot:     'bg-red-600 text-white',
  Justice:     'bg-sky-600 text-white',
  Hermit:      'bg-stone-600 text-white',
  Fortune:     'bg-purple-600 text-white',
  Strength:    'bg-amber-600 text-white',
  Hanged:      'bg-teal-700 text-white',
  Death:       'bg-gray-800 text-white',
  Temperance:  'bg-cyan-700 text-white',
  Devil:       'bg-red-900 text-white',
  Tower:       'bg-zinc-700 text-white',
  Star:        'bg-indigo-600 text-white',
  Moon:        'bg-violet-700 text-white',
  Sun:         'bg-yellow-500 text-slate-900',
  Judgement:   'bg-slate-400 text-slate-900',
  Aeon:        'bg-emerald-600 text-white',
  Jester:      'bg-rose-800 text-white',
  World:       'bg-gradient-to-r from-yellow-500 to-amber-400 text-slate-900',
};

export const ELEM_LABELS: Record<string, string> = {
  phy: 'Phys',
  fir: 'Fire',
  ice: 'Ice',
  ele: 'Elec',
  win: 'Wind',
  lig: 'Light',
  dar: 'Dark',
  alm: 'Almighty',
  ail: 'Ailment',
  rec: 'Recovery',
  sup: 'Support',
  spe: 'Special',
  pas: 'Passive',
};

export const ELEM_COLORS: Record<string, string> = {
  phy: 'bg-orange-800',
  fir: 'bg-red-700',
  ice: 'bg-blue-600',
  ele: 'bg-yellow-600',
  win: 'bg-emerald-600',
  lig: 'bg-amber-400 text-slate-900',
  dar: 'bg-purple-900',
  alm: 'bg-slate-600',
  ail: 'bg-green-800',
  rec: 'bg-teal-700',
  sup: 'bg-indigo-700',
  spe: 'bg-rose-700',
  pas: 'bg-stone-600',
};
